export const languages = {
  en: {
    name: 'English',
    verification: 'none',
    nativeName: 'English',
    translations: {
      // Auth
      'Sign up': 'Sign up',
      'Log in': 'Log in',
      'Email': 'Email',
      'Password': 'Password',
      'Display Name': 'Display Name',
      'Forgot Password?': 'Forgot Password?',
      // Posts
      'Create Post': 'Create Post',
      "What's on your mind?": "What's on your mind?",
      'Add Photo/Video': 'Add Photo/Video',
      'Post': 'Post',
      'Posting...': 'Posting...',
      'Likes': 'Likes',
      'Comments': 'Comments',
      'Share': 'Share',
      'Write a comment...': 'Write a comment...',
      // Navigation
      'Home': 'Home',
      'Questions': 'Questions',
      'Tags': 'Tags',
      'Users': 'Users',
      'About': 'About',
      'Profile': 'Profile',
      'Logout': 'Logout',
      // Profile
      'Edit Profile': 'Edit Profile',
      'Public Information': 'Public Information',
      'About me': 'About me',
      'Watched tags': 'Watched tags',
      'Save profile': 'Save profile',
      'Cancel': 'Cancel',
    }
  },
  fr: {
    name: 'French',
    verification: 'email',
    nativeName: 'Français',
    translations: {
      // Auth
      'Sign up': "S'inscrire",
      'Log in': 'Se connecter',
      'Email': 'Email',
      'Password': 'Mot de passe',
      'Display Name': "Nom d'affichage",
      'Forgot Password?': 'Mot de passe oublié?',
      // Posts
      'Create Post': 'Créer une publication',
      "What's on your mind?": "Que voulez-vous partager?",
      'Add Photo/Video': 'Ajouter photo/vidéo',
      'Post': 'Publier',
      'Posting...': 'Publication...',
      'Likes': "J'aime",
      'Comments': 'Commentaires',
      'Share': 'Partager',
      'Write a comment...': 'Écrire un commentaire...',
      // Navigation
      'Home': 'Accueil',
      'Questions': 'Questions',
      'Tags': 'Tags',
      'Users': 'Utilisateurs',
      'About': 'À propos',
      'Profile': 'Profil',
      'Logout': 'Déconnexion',
      // Profile
      'Edit Profile': 'Modifier le profil',
      'Public Information': 'Informations publiques',
      'About me': 'À propos de moi',
      'Watched tags': 'Tags suivis',
      'Save profile': 'Enregistrer le profil',
      'Cancel': 'Annuler',
    }
  },
  es: {
    name: 'Spanish',
    verification: 'phone',
    nativeName: 'Español',
    translations: {
      // Auth
      'Sign up': 'Registrarse',
      'Log in': 'Iniciar sesión',
      'Email': 'Correo electrónico',
      'Password': 'Contraseña',
      'Display Name': 'Nombre para mostrar',
      'Forgot Password?': '¿Olvidaste tu contraseña?',
      // Posts
      'Create Post': 'Crear publicación',
      "What's on your mind?": "¿Qué estás pensando?",
      'Add Photo/Video': 'Agregar foto/video',
      'Post': 'Publicar',
      'Posting...': 'Publicando...',
      'Likes': 'Me gusta',
      'Comments': 'Comentarios',
      'Share': 'Compartir',
      'Write a comment...': 'Escribe un comentario...',
      // Navigation
      'Home': 'Inicio',
      'Questions': 'Preguntas',
      'Tags': 'Etiquetas',
      'Users': 'Usuarios',
      'About': 'Acerca de',
      'Profile': 'Perfil',
      'Logout': 'Cerrar sesión',
      // Profile
      'Edit Profile': 'Editar perfil',
      'Public Information': 'Información pública',
      'About me': 'Sobre mí',
      'Watched tags': 'Etiquetas seguidas',
      'Save profile': 'Guardar perfil',
      'Cancel': 'Cancelar',
    }
  },
  hi: {
    name: 'Hindi',
    verification: 'phone',
    nativeName: 'हिन्दी',
    translations: {
      // Auth
      'Sign up': 'साइन अप करें',
      'Log in': 'लॉग इन करें',
      'Email': 'ईमेल',
      'Password': 'पासवर्ड',
      'Display Name': 'प्रदर्शन नाम',
      'Forgot Password?': 'पासवर्ड भूल गए?',
      // Posts
      'Create Post': 'पोस्ट बनाएं',
      "What's on your mind?": "आप क्या सोच रहे हैं?",
      'Add Photo/Video': 'फोटो/वीडियो जोड़ें',
      'Post': 'पोस्ट करें',
      'Posting...': 'पोस्ट कर रहे हैं...',
      'Likes': 'लाइक्स',
      'Comments': 'टिप्पणियाँ',
      'Share': 'शेयर करें',
      'Write a comment...': 'टिप्पणी लिखें...',
      // Navigation
      'Home': 'होम',
      'Questions': 'प्रश्न',
      'Tags': 'टैग',
      'Users': 'उपयोगकर्ता',
      'About': 'हमारे बारे में',
      'Profile': 'प्रोफ़ाइल',
      'Logout': 'लॉग आउट',
      // Profile
      'Edit Profile': 'प्रोफ़ाइल संपादित करें',
      'Public Information': 'सार्वजनिक जानकारी',
      'About me': 'मेरे बारे में',
      'Watched tags': 'देखे गए टैग',
      'Save profile': 'प्रोफ़ाइल सहेजें',
      'Cancel': 'रद्द करें',
    }
  },
  pt: {
    name: 'Portuguese',
    verification: 'phone',
    nativeName: 'Português',
    translations: {
      // Auth
      'Sign up': 'Cadastrar',
      'Log in': 'Entrar',
      'Email': 'Email',
      'Password': 'Senha',
      'Display Name': 'Nome de exibição',
      'Forgot Password?': 'Esqueceu a senha?',
      // Posts
      'Create Post': 'Criar publicação',
      "What's on your mind?": "O que você está pensando?",
      'Add Photo/Video': 'Adicionar foto/vídeo',
      'Post': 'Publicar',
      'Posting...': 'Publicando...',
      'Likes': 'Curtidas',
      'Comments': 'Comentários',
      'Share': 'Compartilhar',
      'Write a comment...': 'Escreva um comentário...',
      // Navigation
      'Home': 'Início',
      'Questions': 'Perguntas',
      'Tags': 'Tags',
      'Users': 'Usuários',
      'About': 'Sobre',
      'Profile': 'Perfil',
      'Logout': 'Sair',
      // Profile
      'Edit Profile': 'Editar perfil',
      'Public Information': 'Informações públicas',
      'About me': 'Sobre mim',
      'Watched tags': 'Tags observadas',
      'Save profile': 'Salvar perfil',
      'Cancel': 'Cancelar',
    }
  },
  zh: {
    name: 'Chinese',
    verification: 'phone',
    nativeName: '中文',
    translations: {
      // Auth
      'Sign up': '注册',
      'Log in': '登录',
      'Email': '电子邮件',
      'Password': '密码',
      'Display Name': '显示名称',
      'Forgot Password?': '忘记密码？',
      // Posts
      'Create Post': '创建帖子',
      "What's on your mind?": "你在想什么？",
      'Add Photo/Video': '添加图片/视频',
      'Post': '发布',
      'Posting...': '发布中...',
      'Likes': '点赞',
      'Comments': '评论',
      'Share': '分享',
      'Write a comment...': '写评论...',
      // Navigation
      'Home': '首页',
      'Questions': '问题',
      'Tags': '标签',
      'Users': '用户',
      'About': '关于',
      'Profile': '个人资料',
      'Logout': '退出',
      // Profile
      'Edit Profile': '编辑资料',
      'Public Information': '公开信息',
      'About me': '关于我',
      'Watched tags': '关注的标签',
      'Save profile': '保存资料',
      'Cancel': '取消',
    }
  }
};
